# ?? ?? ??
server:
  port: 8082

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bus?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/springboot_img/images/

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: debug
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
  file : ${user.home}/logs/product.log
  file.max-history: 9999999
  file.max-size : 100MB
